import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. import GoogleAnalytics เข้ามา
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Free App",
  description: "Generated by create app for free",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* 2. แทรกส่วนนี้เข้าไปก่อนปิด </body> (อย่าลืมเปลี่ยน G-XXXXXXXXXX เป็น ID จริง) */}
        <GoogleAnalytics gaId="G-KYKHVFKJEH" />
      </body>
    </html>
  );
}